// ===== Аудармалар =====
const I18N = {
  kz: {
    nav_menu: "Мәзір", nav_reviews: "Пікірлер", nav_contacts: "Байланыс",
    tagline: "Үздік фаст фуд · 2025",
    hero_title: "Құлсарының №1 фаст фуды",
    hero_sub: "Балғын ингредиенттер, фирмалық соустар, шынайы дәм. 24/7 — ұйықтамаймыз, аштықпен қалдырмаймыз.",
    hero_cta: "Тапсырыс беру",
    badge_open: "24 · 7 · 365",
    badge_fast: "🔥 Дайын — 15 мин",
    why_title: "Неге Dailizza?",
    why_1_t: "Үздіксіз 24/7",
    why_1_d: "Түнгі 3-те қарным ашты ма? Біз ашықпыз. Жаңа жыл, мейрам — бәрібір ашықпыз.",
    why_2_t: "Балғын дәм",
    why_2_d: "Тек балғын ингредиенттер. Күн сайын жаңасы. Мұздатылғаны жоқ.",
    why_3_t: "Жылдам жеткізу",
    why_3_d: "Тапсырыс — 5 минут, дайын — 15 минут. Құлсары бойынша жеткіземіз.",
    why_4_t: "Фирмалық соустар",
    why_4_d: "Біздің құпиямыз — үйде жасалған соустар. Басқа жерде таппайсыз.",

    cat_doner: "Донер", cat_baton: "Донер в Батоне", cat_burger: "Бургер & Твистер",
    cat_bowl: "Боул & Салат", cat_wings: "Қанаттар", cat_pizza: "Пицца",
    cat_hotdog: "Хот-Дог", cat_snack: "Snacks", cat_drinks: "Сусындар",
    cat_combo: "Комбо", cat_set: "Пицца жинағы",
    add: "Қосу",
    cart: "Корзина", cart_empty: "Корзина бос",
    total: "Жалпы сома", checkout: "WhatsApp-қа жіберу",
    order_form: "Тапсырыс рәсімдеу", delivery_type: "Алу түрі",
    pickup: "Өзім аламын", delivery: "Жеткізу",
    address: "Мекенжай", address_ph: "Көше, үй, пәтер",
    phone: "Удаленка жіберілетін номер", phone_ph: "+7 ___ ___ __ __",
    bank_label: "Қай банкпен жібересіз",
    bank_kaspi: "Kaspi", bank_halyk: "Halyk",
    msg_bank: "Банк:",
    name_label: "Атыңыз", name_ph: "Атыңыз",
    date: "Күні", time: "Уақыты",
    comment: "Түсініктеме", comment_ph: "Қосымша сұрау (міндетті емес)",
    send: "WhatsApp-қа жіберу",
    review_title: "Пікірлер", review_sub: "Бізге пікір қалдырыңыз",
    review_name: "Атыңыз", review_text: "Пікіріңіз",
    review_photo: "Фото",
    review_camera: "Камера", review_gallery: "Галерея",
    review_send: "Жіберу",
    no_reviews: "Әзірге пікір жоқ. Бірінші болыңыз!",
    contacts_title: "Байланыс", address_label: "Мекенжай",
    work_hours: "Жұмыс уақыты", open247: "24 / 7 / 365",
    tenge: "₸",
    msg_intro: "Сәлеметсіз бе! Dailizza-дан тапсырыс:",
    msg_items: "Тапсырыс:", msg_total: "Жалпы:",
    msg_type: "Алу түрі:", msg_addr: "Мекенжай:",
    msg_name: "Аты:", msg_phone: "Телефон:",
    msg_date: "Күні:", msg_time: "Уақыты:", msg_comment: "Түсініктеме:",
    fill_required: "Міндетті өрістерді толтырыңыз",
    review_added: "Пікіріңіз қосылды, рахмет!",
    fab_text: "Корзина",
    city: "Құлсары",
  },
  ru: {
    nav_menu: "Меню", nav_reviews: "Отзывы", nav_contacts: "Контакты",
    tagline: "Лучший фастфуд · 2025",
    hero_title: "Фастфуд №1 в Кульсары",
    hero_sub: "Свежие ингредиенты, фирменные соусы, настоящий вкус. 24/7 — не спим, голодными не оставим.",
    hero_cta: "Заказать",
    badge_open: "24 · 7 · 365",
    badge_fast: "🔥 Готово за 15 мин",
    why_title: "Почему Dailizza?",
    why_1_t: "Открыто 24/7",
    why_1_d: "Голод в 3 ночи? Мы открыты. Новый год, праздник — всё равно работаем.",
    why_2_t: "Свежий вкус",
    why_2_d: "Только свежие ингредиенты. Каждый день новые. Без заморозки.",
    why_3_t: "Быстрая доставка",
    why_3_d: "Заказ — 5 минут, готовка — 15. Доставим по всему Кульсары.",
    why_4_t: "Фирменные соусы",
    why_4_d: "Наш секрет — домашние соусы. Такого нигде больше не попробуете.",

    cat_doner: "Донер", cat_baton: "Донер в Батоне", cat_burger: "Бургер & Твистер",
    cat_bowl: "Боул & Салат", cat_wings: "Крылышки", cat_pizza: "Пицца",
    cat_hotdog: "Хот-Дог", cat_snack: "Snacks", cat_drinks: "Напитки",
    cat_combo: "Комбо", cat_set: "Собирай пиццу сам",
    add: "Добавить",
    cart: "Корзина", cart_empty: "Корзина пуста",
    total: "Итого", checkout: "Отправить в WhatsApp",
    order_form: "Оформление заказа", delivery_type: "Способ получения",
    pickup: "Самовывоз", delivery: "Доставка",
    address: "Адрес", address_ph: "Улица, дом, квартира",
    phone: "Номер для перевода (Удаленка)", phone_ph: "+7 ___ ___ __ __",
    bank_label: "Через какой банк отправите",
    bank_kaspi: "Kaspi", bank_halyk: "Halyk",
    msg_bank: "Банк:",
    name_label: "Ваше имя", name_ph: "Имя",
    date: "Дата", time: "Время",
    comment: "Комментарий", comment_ph: "Дополнительное пожелание (необязательно)",
    send: "Отправить в WhatsApp",
    review_title: "Отзывы", review_sub: "Оставьте свой отзыв",
    review_name: "Ваше имя", review_text: "Ваш отзыв",
    review_photo: "Фото",
    review_camera: "Камера", review_gallery: "Галерея",
    review_send: "Отправить",
    no_reviews: "Пока нет отзывов. Будьте первым!",
    contacts_title: "Контакты", address_label: "Адрес",
    work_hours: "Часы работы", open247: "24 / 7 / 365",
    tenge: "₸",
    msg_intro: "Здравствуйте! Заказ с Dailizza:",
    msg_items: "Заказ:", msg_total: "Итого:",
    msg_type: "Способ получения:", msg_addr: "Адрес:",
    msg_name: "Имя:", msg_phone: "Телефон:",
    msg_date: "Дата:", msg_time: "Время:", msg_comment: "Комментарий:",
    fill_required: "Заполните обязательные поля",
    review_added: "Спасибо, ваш отзыв добавлен!",
    fab_text: "Корзина",
    city: "Кульсары",
  }
};

const CATS = ["doner","baton","burger","bowl","wings","pizza","hotdog","snack","drinks","combo","set"];

const MENU = [
  // ===== DONER =====
  { type:"group", cat:"doner", img:"doner.jpg",
    title:{kz:"Донер", ru:"Донер"},
    items:[
      { id:"doner-kur", name:{kz:"Донер Куриный",ru:"Донер Куриный"}, price:1690,
        desc:{kz:"Тауық еті, фри, фирмалық соус, тұздалған қияр, лаваш",
              ru:"Куриное мясо, картофель фри, фирменный соус, соленые огурцы, лаваш"}},
      { id:"doner-gov", isNew:true, name:{kz:"Донер Говяжий",ru:"Донер Говяжий"}, price:2390,
        desc:{kz:"Сиыр еті, фри, фирмалық соус, тұздалған қияр, лаваш",
              ru:"Мясо говядина, фри, фирменный соус, соленые огурцы, лаваш"}},
      { id:"doner-ass", isNew:true, name:{kz:"Донер Ассорти",ru:"Донер Ассорти"}, price:2190,
        desc:{kz:"Тауық + сиыр, фри, фирмалық соус, тұздалған қияр, лаваш",
              ru:"Куриное и говяжье мясо, фри, фирменный соус, соленые огурцы, лаваш"}},
    ]
  },

  // ===== BATON =====
  { type:"group", cat:"baton", img:"baton.jpg",
    title:{kz:"Донер в Батоне", ru:"Донер в Батоне"},
    items:[
      { id:"baton-kur", isNew:true, name:{kz:"Батон Куриный",ru:"Батон Куриный"}, price:1690,
        desc:{kz:"Тауық, қызанақ, тұздалған қияр, фирмалық қызыл және ақ соус, батон",
              ru:"Курица, помидор, соленый огурец, фирменный красный и белый соус, батон"}},
      { id:"baton-gov", isNew:true, name:{kz:"Батон Говяжий",ru:"Батон Говяжий"}, price:2390,
        desc:{kz:"Сиыр еті, фирмалық соус, балғын қызанақ, батон",
              ru:"Говядина, фирменный соус, свежий помидор, батон"}},
      { id:"baton-ass", isNew:true, name:{kz:"Батон Ассорти",ru:"Батон Ассорти"}, price:2190,
        desc:{kz:"Тауық + сиыр, фирмалық соус, балғын қызанақ, батон",
              ru:"Куриное + говяжье мясо, фирменный соус, свежий помидор, батон"}},
    ]
  },

  // ===== BURGERS — 4 жеке карточка =====
  { type:"item", cat:"burger", img:"burger-gov.jpg", id:"burger-gov",
    name:{kz:"Бургер Говяжий",ru:"Бургер Говяжий"},
    desc:{kz:"Тоқаш, сиыр котлета, ірімшік, айсберг, қызанақ, пісірілген пияз, бургер соус",
          ru:"Булочка, говяжья котлета, плавленый сыр, айсберг, помидоры, жареный лук, бургер соус"},
    sizes:[ {label:"1x", price:2090}, {label:"2x", price:2590, isNew:true} ] },

  { type:"item", cat:"burger", img:"burger-kur.jpg", id:"burger-kur",
    name:{kz:"Бургер Куриный",ru:"Бургер Куриный"},
    desc:{kz:"Тоқаш, тауық котлета, ірімшік, айсберг, қызанақ, пісірілген пияз, бургер соус",
          ru:"Булочка, куриная котлета, плавленый сыр, айсберг, помидоры, жареный лук, бургер соус"},
    sizes:[ {label:"1x", price:1690}, {label:"2x", price:2090, isNew:true} ] },

  { type:"item", cat:"burger", img:"burger-close.jpg", id:"burger-close", isNew:true,
    name:{kz:"Бургер Закрытый",ru:"Бургер Закрытый"}, price:1890,
    desc:{kz:"Тоқаш, сиыр котлета, ірімшік, жұмыртқа, қызанақ, бургер соус",
          ru:"Булочка, говяжья котлета, плавленый сыр, яичница, помидоры, бургер соус"}},

  { type:"item", cat:"burger", img:"burger-chick.jpg", id:"burger-chick",
    name:{kz:"Бургер Чикен",ru:"Бургер Чикен"}, price:1590,
    desc:{kz:"Панировкадағы тауық филесі, ірімшік, айсберг, қызанақ, пияз, бургер соус",
          ru:"Куриное филе в панировке, сыр, айсберг, помидоры, жареный лук, соус"}},

  // ===== Twister & Boxmaster =====
  { type:"item", cat:"burger", img:"strips.jpg", id:"twister",
    name:{kz:"Твистер",ru:"Твистер"}, price:1590,
    desc:{kz:"Стрипстер, фри, ірімшік, қызанақ, айсберг, фирмалық соус, лепешка",
          ru:"Стрипсы, фри, сыр, помидоры, айсберг, фирменные соусы, лепешка"}},
  { type:"item", cat:"burger", img:"boxmaster.jpg", id:"boxmaster",
    name:{kz:"Бокс Мастер",ru:"Бокс Мастер"}, price:1690,
    desc:{kz:"Тауық филесі, айсберг, қызанақ, ірімшік, хашбраун, лепешка",
          ru:"Куриное филе, айсберг, помидоры, сыр, хашбраун в лепешке"}},

  // ===== BOWL & САЛАТ =====
  { type:"item", cat:"bowl", img:"bowl-rice.jpg", id:"bowl-rice", isNew:true,
    name:{kz:"Боул күрішпен",ru:"Боул с рисом"}, price:1690,
    desc:{kz:"Тауық, күріш, ірімшік, көкөніс, фирмалық соус",
          ru:"Курица, рис, сыр, овощи, фирменный соус"}},
  { type:"item", cat:"bowl", img:"bowl-fri.jpg", id:"caesar", isNew:true,
    name:{kz:"Цезарь салаты",ru:"Салат Цезарь"}, price:1690,
    desc:{kz:"Айсберг, черри қызанақ, сухарик, пармезан, тауық стрипстер",
          ru:"Айсберг, черри, сухарики, пармезан, куриные стрипсы"}},
  { type:"list", cat:"bowl",
    title:{kz:"Тағы",ru:"Ещё"},
    items:[
      { id:"bowl-fri", name:{kz:"Боул фримен",ru:"Боул с фри"}, price:1690,
        desc:{kz:"Тауық, фри, ірімшік, көкөніс, фирмалық соус",
              ru:"Курица, фри, сыр, овощи, фирменный соус"}},
    ]
  },

  // ===== SNACKS =====
  { type:"item", cat:"snack", img:"fri.jpg", id:"fri-150",
    name:{kz:"Картоп Фри",ru:"Картофель Фри"}, price:790,
    desc:{kz:"150 г, хрусткі",ru:"150 г, хрустящий"}},
  { type:"item", cat:"snack", img:"strips.jpg", id:"strips-3",
    name:{kz:"Стрипсы 3 шт",ru:"Стрипсы 3 шт"}, price:1690,
    desc:{kz:"Хрусткі тауық стрипстері",ru:"Хрустящие куриные стрипсы"}},
  { type:"list", cat:"snack",
    title:{kz:"Тағы",ru:"Ещё"},
    items:[
      { id:"onion-rings", isNew:true, name:{kz:"Луковые кольца 5 шт",ru:"Луковые кольца 5 шт"}, price:590,
        desc:{kz:"Хрусткі пияз сақиналары",ru:"Хрустящие луковые кольца"}},
    ]
  },

  // ===== WINGS =====
  { type:"group", cat:"wings", img:"wings-classic.jpg",
    title:{kz:"Қанаттар (классика)",ru:"Крылышки (классика)"},
    items:[
      { id:"wings-10", name:{kz:"Крылышки 10 шт",ru:"Крылышки 10 шт"}, price:3290, desc:{kz:"Фирмалық соуспен",ru:"С фирменным соусом"}},
      { id:"wings-15", name:{kz:"Крылышки 15 шт",ru:"Крылышки 15 шт"}, price:4290, desc:{kz:"Фирмалық соуспен",ru:"С фирменным соусом"}},
      { id:"wings-25", name:{kz:"Крылышки 25 шт",ru:"Крылышки 25 шт"}, price:6290, desc:{kz:"Фирмалық соуспен",ru:"С фирменным соусом"}},
    ]
  },
  { type:"group", cat:"wings", img:"wings-sweet.jpg",
    title:{kz:"Қанаттар тәтті-қышқыл",ru:"Крылышки кисло-сладкие"},
    items:[
      { id:"wings-sweet-10", name:{kz:"Крылышки кисло-сладкие 10 шт",ru:"Крылышки кисло-сладкие 10 шт"}, price:3690, desc:{kz:"Гарнир — картоп",ru:"Гарнир — картофель"}},
      { id:"wings-sweet-15", name:{kz:"Крылышки кисло-сладкие 15 шт",ru:"Крылышки кисло-сладкие 15 шт"}, price:4690, desc:{kz:"Гарнир — картоп",ru:"Гарнир — картофель"}},
      { id:"wings-sweet-25", name:{kz:"Крылышки кисло-сладкие 25 шт",ru:"Крылышки кисло-сладкие 25 шт"}, price:6690, desc:{kz:"Гарнир — картоп",ru:"Гарнир — картофель"}},
    ]
  },

  // ===== PIZZA — фотомен 5 =====
  { type:"item", cat:"pizza", img:"pizza-marg.jpg", id:"pizza-marg", isNew:true,
    name:{kz:"Маргарита",ru:"Маргарита"}, price:2890,
    desc:{kz:"Томат соусы, моцарелла, базилик",ru:"Томат, моцарелла, базилик"}},
  { type:"item", cat:"pizza", img:"pizza-bolognese.jpg", id:"pizza-bol", isNew:true,
    name:{kz:"Болоньезе",ru:"Болоньезе"}, price:3290,
    desc:{kz:"Болонез соусы, моцарелла, ет фарш",ru:"Соус болоньезе, моцарелла, мясной фарш"}},
  { type:"item", cat:"pizza", img:"pizza-bird.jpg", id:"pizza-bird", isNew:true,
    name:{kz:"Птичка в булке",ru:"Птичка в булке"}, price:3290,
    desc:{kz:"Балапан, сарымсақ, томат, моцарелла, бургер соус, Альфредо",
          ru:"Цыпленок, чеснок, томат, моцарелла, бургер соус, Альфредо"}},
  { type:"item", cat:"pizza", img:"pizza-imp.jpg", id:"pizza-imp", isNew:true,
    name:{kz:"Императорская",ru:"Императорская"}, price:4590,
    desc:{kz:"Сиыр еті, BBQ соустағы пияз, моцарелла, пицца соусы",
          ru:"Говядина, жареный лук в BBQ, моцарелла, пицца соус"}},
  { type:"item", cat:"pizza", img:"pizza-fil.jpg", id:"pizza-fil", isNew:true,
    name:{kz:"Филадельфия",ru:"Филадельфия"}, price:4090,
    desc:{kz:"Сёмга, ірімшік, терияки, руккола, моцарелла",
          ru:"Семга, творожный сыр, терияки, руккола, моцарелла"}},

  // ===== PIZZA — фотосыз =====
  { type:"list", cat:"pizza",
    title:{kz:"Тағы пицца",ru:"Ещё пиццы"},
    items:[
      { id:"pizza-pep", isNew:true, name:{kz:"Пепперони",ru:"Пепперони"}, price:3090,
        desc:{kz:"Пепперони, моцарелла, томат соусы",ru:"Пепперони, моцарелла, томат"}},
      { id:"pizza-bas", isNew:true, name:{kz:"Basilico престиж",ru:"Basilico престиж"}, price:4290,
        desc:{kz:"Песто, Альфредо, балапан, брынза, томат, моцарелла",
              ru:"Песто, Альфредо, цыпленок, брынза, томат, моцарелла"}},
      { id:"pizza-jul", isNew:true, name:{kz:"Жульен",ru:"Жульен"}, price:3190,
        desc:{kz:"Томат соусы, моцарелла, балапан, қызыл пияз, маринад, қызанақ",
              ru:"Томат, моцарелла, цыпленок, красный лук, маринованные, помидоры"}},
      { id:"pizza-cheese", isNew:true, name:{kz:"Сырная",ru:"Сырная"}, price:3290,
        desc:{kz:"Альфредо, моцарелла, моцарелла рассолда, чеддер",
              ru:"Альфредо, моцарелла, моцарелла в рассоле, чеддер"}},
      { id:"pizza-meat", isNew:true, name:{kz:"Мясные шарики",ru:"Мясные шарики"}, price:3890,
        desc:{kz:"Моцарелла, ет шарлары, карамель пияз, шампиньон",
              ru:"Моцарелла, мясные шарики, карамельный лук, шампиньоны"}},
    ]
  },

  // ===== HOT DOG =====
  { type:"item", cat:"hotdog", img:"hd-class.jpg", id:"hd-class", isNew:true,
    name:{kz:"Хот-Дог Классический",ru:"Хот-Дог Классический"}, price:1490,
    desc:{kz:"Тоқаш, сиыр сосискасы, қыша, кетчуп, пісірілген пияз, ақ соус",
          ru:"Булочка, говяжьи сосиски, горчица, кетчуп, жареный лук, белый соус"}},
  { type:"item", cat:"hotdog", img:"hd-mex.jpg", id:"hd-mex", isNew:true,
    name:{kz:"Хот-Дог Мексиканский",ru:"Хот-Дог Мексиканский"}, price:1890,
    desc:{kz:"Тоқаш, сиыр сосискасы, ет фарш, моцарелла, халапеньо, ақ соус",
          ru:"Булочка, гов. сосиска, гов. фарш, моцарелла, халапеньо, белый соус"}},
  { type:"item", cat:"hotdog", img:"hd-chick.jpg", id:"hd-chick", isNew:true,
    name:{kz:"Чикен Дог",ru:"Чикен Дог"}, price:1690,
    desc:{kz:"Тоқаш, фри, стрипстер, айсберг, ақ соус, ірімшік соусы",
          ru:"Булка, фри, стрипсы, айсберг, белый соус, сырный соус"}},
  { type:"item", cat:"hotdog", img:"hd-assorti.jpg", id:"hd-ass", isNew:true,
    name:{kz:"Ассорти Дог",ru:"Ассорти Дог"}, price:1890,
    desc:{kz:"Тауық еті, сиыр сосискасы, ақ соус, тұздалған қияр",
          ru:"Куриное мясо, говяжья сосиска, белый соус, соленые огурцы"}},
  { type:"item", cat:"hotdog", img:"hd-ny.jpg", id:"hd-ny", isNew:true,
    name:{kz:"Хот-Дог New York",ru:"Хот-Дог New York"}, price:1890,
    desc:{kz:"Тоқаш, сиыр сосискасы, чеддер, айсберг, қыша, кетчуп, ақ соус",
          ru:"Булочка, говяжья сосиска, чеддер, айсберг, горчица, кетчуп, белый соус"}},

  // ===== DRINKS =====
  // Напитки — бөтелкедегі сусындар
  { type:"group", cat:"drinks", img:"drinks-bottles.jpg",
    title:{kz:"Напитки",ru:"Напитки"},
    items:[
      { id:"ayran",    name:{kz:"Айран",ru:"Айран"}, price:390,
        desc:{kz:"0,3 л",ru:"0,3 л"}},
      { id:"pepsi-1l", name:{kz:"Pepsi 1 л",ru:"Pepsi 1 л"}, price:890,
        desc:{kz:"",ru:""}},
      { id:"lipton",   name:{kz:"Lipton 1 л",ru:"Lipton 1 л"}, price:890,
        desc:{kz:"",ru:""}},
      { id:"pepsi-05", name:{kz:"Pepsi 0,5",ru:"Pepsi 0,5"}, price:690,
        desc:{kz:"Бөтелке",ru:"Бутылка"}},
      { id:"asu-1l",   name:{kz:"Asu су 1 л",ru:"Asu вода 1 л"}, price:690, isNew:true,
        desc:{kz:"Таза су",ru:"Питьевая вода"}},
    ]
  },

  // Разливной — Dailizza ыдысы
  { type:"group", cat:"drinks", img:"razliv-dailizza.jpg",
    title:{kz:"Разливной",ru:"Разливной"},
    items:[
      { id:"razliv-pepsi", name:{kz:"Pepsi 0,5",ru:"Pepsi 0,5"}, price:690, desc:{kz:"",ru:""}},
      { id:"razliv-mer",  name:{kz:"Merinda 0,5",ru:"Merinda 0,5"}, price:690, desc:{kz:"",ru:""}},
      { id:"razliv-7up",  name:{kz:"7Up 0,5",ru:"7Up 0,5"}, price:690, desc:{kz:"",ru:""}},
      { id:"razliv-ice",  name:{kz:"Ice Tea 0,5",ru:"Ice Tea 0,5"}, price:690, desc:{kz:"",ru:""}},
    ]
  },

  // ===== COMBO =====
  { type:"list", cat:"combo",
    title:{kz:"Комбо",ru:"Комбо"},
    items:[
      { id:"combo-burger", isNew:true, name:{kz:"Бургер комбо",ru:"Комбо Бургер"}, price:3390,
        desc:{kz:"Сиыр бургер + Фри + Pepsi 0,5",ru:"Бургер говяжий + Фри + Pepsi 0,5"}},
      { id:"combo-doner", isNew:true, name:{kz:"Донер комбо",ru:"Комбо Донер"}, price:3290,
        desc:{kz:"Куриный донер + Фри L + Айран 0,3",ru:"Донер куриный + Фри L + Айран 0,3"}},
      { id:"combo-twist", isNew:true, name:{kz:"Твистер комбо",ru:"Комбо Твистер"}, price:2690,
        desc:{kz:"Твистер + Фри + Pepsi 0,5",ru:"Твистер + Фри + Pepsi 0,5"}},
      { id:"combo-2", isNew:true, name:{kz:"Екеуге комбо",ru:"Комбо на двоих"}, price:5290,
        desc:{kz:"2 донер + Фри L + 2 × Pepsi 0,5",ru:"2 донера + Фри L + 2 × Pepsi 0,5"}},
      { id:"combo-daily", isNew:true, name:{kz:"Daily Комбо",ru:"Daily Комбо"}, price:6190,
        desc:{kz:"Қанаттар 15 дана + Фри L + 2 × Pepsi 0,5",ru:"Крылышки 15 шт + Фри L + 2 × Pepsi 0,5"}},
    ]
  },

  // ===== PIZZA SET =====
  { type:"list", cat:"set",
    title:{kz:"Пицца жинағы",ru:"Собирай пиццу сам"},
    items:[
      { id:"set-3", name:{kz:"3 пицца + 1 л Pepsi",ru:"3 пиццы + 1 л Pepsi"}, price:9000, desc:{kz:"",ru:""}},
      { id:"set-5", name:{kz:"5 пицца + 2 л Pepsi",ru:"5 пицц + 2 л Pepsi"}, price:14000, desc:{kz:"",ru:""}},
      { id:"set-7", name:{kz:"7 пицца + 3 л Pepsi",ru:"7 пицц + 3 л Pepsi"}, price:24000, desc:{kz:"",ru:""}},
    ]
  },
];

const CONTACT = {
  whatsapp: "77710552525",
  whatsapp_display: "+7 771 055 25 25",
  instagram: "https://www.instagram.com/dailizza.24.7?igsh=NDN1ZWI1aXc0NG1i",
  instagram_handle: "@dailizza.24.7",
  twogis: "https://2gis.kz/atyrau/geo/70000001102442551/54.023850,46.958001",
  address_text: "Құлсары, Dailizza",
};
